name: CI/CD

on:
  push:
    branches:
      - feature/ci-cd-david
      - feature/routes-david
      - feature/models-isaac
      - main
      
  pull_request:
    branches:
      - feature/ci-cd-david
      - feature/routes-david
      - feature/models-isaac
      - main
     
      

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy to Render here..."


  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: CI=true npm test
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy to Vercel here..."


